"""<message>
Revision ID: 04fa31db1a22
Revises: d73195ca0772
Create Date: 2023-05-07 16:37:20.805208
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '04fa31db1a22'
down_revision = 'd73195ca0772'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'info_before_confirm_ticket',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'info_before_confirm_ticket',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###