"""fix event
Revision ID: b6fe33debed2
Revises: 4ac6ea9427ba
Create Date: 2023-04-07 22:13:57.632151
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = 'b6fe33debed2'
down_revision = '4ac6ea9427ba'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'aditional_location_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'aditional_location_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###