"""fix event
Revision ID: d73195ca0772
Revises: b6fe33debed2
Create Date: 2023-04-07 22:14:47.781172
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = 'd73195ca0772'
down_revision = 'b6fe33debed2'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###